language: node_js

node_js:
  - "0.10"
  - "0.12"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

env:
  global:
    - TEST_FUNC_PORT=3030
    - TEST_FUNC_HOST=127.0.0.1
    - SAUCE_CONNECT_TUNNEL_ID=$TRAVIS_JOB_NUMBER
    - SAUCE_USERNAME=requirepack
    - secure: "Gg2no6CkOreDPINT4xoJQPV/93Wq7MxZ7fwgATucuze9KYdidJaKFY8nEx3oJshFtPZ6t46JXxlVrR6n9De720R5RefHUBpuSVVzDedXsdYHXyjh6eNj1z88zteUcLp62hGipvAOrXUeC/l8OuCMCjeqIJtICYF4VJF7RlOyc5RnONOID0u62bogaGnwnHqTH/NlBVLjYDvPGrHhX2FB0TNQaRA89AaE69GyaCSFunEigpA48b/ogfHTF6OfHIvAvtLZf1hrQxGrf854snsqi/yi7+3Kz0m6EABINVGNmD29FqPteR5o7ZPquXt8A8IicL8omFM0jxgU4ma0hRFPvzZLaApFpsCtKfkN9h75LvFkTHkBNXXlaS/ZGMgxWzng6x7jOHxnoczoC2GrqPB48H0kZggHUa7O10gFhmmkbJOywAWv+X2cUaINL/Zn/mxons3JKa1ojb4DDT05TlpUDKv/zPhCAg0fB35GR2/XaZXs1wA8/2fA11VHHfB8Wea91sV+V+3L4H3PD5UueHEV4pE40t54GkjrLVr1OSFIqkDjgVHEkmHJQrx9uVoON6uWT7TwNNK9v2Nt9pRyIYFlHdm1S7pb6h279meN7NC9DueMXp3CYzTwWPgzHGg032tBZ8ga4Nr7wLYZu40Ql+h7D3aw4TWKyPNRo5YM3HkxqRc="

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  # Install dev. stuff (e.g., selenium drivers).
  - npm run install-dev
  - nohup bash -c "node_modules/.bin/selenium-standalone start 2>&1 &"
  - nohup bash -c "node_modules/.bin/http-server -a $TEST_FUNC_HOST -p $TEST_FUNC_PORT --silent 2>&1 &"

addons:
  sauce_connect: true

script:
  # Run all base checks (with FF browser for functional tests).
  - npm run check-ci

  # Sauce Labs
  - >-
    node test/util/run-concurrent.js "npm run test-func"
    '[ { "ROWDY_SETTINGS":"sauceLabs.IE_8_Windows_2008_Desktop" },
    { "ROWDY_SETTINGS":"sauceLabs.IE_9_Windows_2008_Desktop" },
    { "ROWDY_SETTINGS":"sauceLabs.IE_10_Windows_2012_Desktop" },
    { "ROWDY_SETTINGS":"sauceLabs.safari_8_OS_X_10_10_Desktop" },
    { "ROWDY_SETTINGS":"sauceLabs.chrome_43_OS_X_10_10_Desktop" },
    { "ROWDY_SETTINGS":"local.firefox" } ]'

  # Manually send coverage reports to coveralls.
  - ls  coverage/*/lcov.info | cat
  - cat coverage/*/lcov.info | ./node_modules/.bin/coveralls || echo "Coveralls upload failed"
