language: node_js

node_js:
  - "0.10"
  - "0.12"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  # Install dev. stuff (e.g., selenium drivers).
  - npm run install-dev

env:
  global:
    - secure: VbnGQuWiljZSw9DrscOL3/eph86TmD5LulP/AhASVzcUB2xZcuK2U4E8OcuY+fMcOcwoNpKqO/e+QIvecr8JwurXKnbr0Hua6EeO/vEOiNTD/l4NmSDqPR4B9y01oARRJW2S+MlDNx5QI7W3tSOiV1wjWtS2RhvsAIPO3kurzUJXU9Yc+sUl8/KoAOflKDJVYgQN1yEHHCBnOs+qHyI7YyN66YTxK51rfvHBV8C14fUqkOjjDJtDoi7y6GgSL8BDTJRf/MNaGE3jJFZEFLxCLbAiuSnwT5nRhr/gGRbmiE2IQcwgTPm8Kul+TBqjwimnHqBGaMNRvkRFG7OmcYI5yXvjY/l+VkCk3etkXIsFLu9CppyflBOKb0G2IkAOBmOgB6/HpQJgOrImxNQ3zn5/xCoKzLexVuCzoIETq7DSFzraxoKGtMOJQTz5rZRdj9RgY2NGHiVjuBiePcuKgFTBfjTHNvVzNayo/kqDHJmw1QNkRsqOIi8uyo22o1N2wILXier4xjT4f5MspEnFNQOt2IGDt/loxh8xWsi4ltetFybBF7y/anVrkD1JqJsg5nrsV/VQsxE1ryfrr7FkJATqq4KYdrH7NrZxYzH5HF4Q/g1zu4ob/EaKrJsUVXiZ6loDsG4K8AblHysSw/Fo77qRog/zcUttYgyAeSRnSy4Nz7o=
    - secure: nbbv8GSe/u7Flq/LNfyg4aJAPWz/xHEBt6yharCaSSDkBjG6FIy9HDefFAAVSlauqzD19xlvanGP7J9yN3yzfE2pdpDkUoYFcIRbq+iYj7p19ne3BfaozDbq/XVqVIOG20TGza0Nn5bjCx906QGy9zaG6qo9pJOjFM/+VlXO3VPGnwRuENXwPQm/1bc213kZ2GsbsRxdZLDOcz/uo1bWpOKvf6nnuxX1/rfDO/u+/ioFxGqvE8h1fsyMYDW5rX9fwKor+XwSHc4ktAuf/VcMIGvZ6KepjqkL/+GukM4I756PX3egl4BQvP1i5pQbWzHnIX+Sl1bKdc+P0e0m7oyXwTB3EupwAtJFjKi0Gbthid4UVJxLh7LhBvj/6V4H+bvMRwx0KI4jm+/p1finAbfST/JN6iYasAGEGCNUZHRQHYNviGGN7eVXbVaArsVAMLenEUJ/TRHaN7M9qV479tFeIyWRtUf7xuujj4aIwMxhG6a5SP3feWh6gZuCgZz/eaidASlE/OBdTg5uk4ye0IRtdK5D7zJC3vG3S7w4IFiBHmgRKz0fRpqVlx7JOj3whIb9P6qcWwuzS49pnFkGHsD/e4pW3E/0f+C89ZjDFSZX42rA7wgw0p3kftQGHn9ySalV2T0rne/em86ZyyQiDTvFRubhp35epC3gI3cv1EK1ouk=

script:
  # Run all base checks (with FF browser for functional tests).
  - npm run check-ci

  # Manually send coverage reports to coveralls.
  - ls  coverage/*/lcov.info | cat
  - cat coverage/*/lcov.info | ./node_modules/.bin/coveralls || echo "Coveralls upload failed"
