language: node_js

node_js:
  - "0.10"
  - "0.12"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  # Install dev. stuff (e.g., selenium drivers).
  - npm run install-dev

script:
  # Run all base checks (with FF browser for functional tests).
  - npm run check-ci

  # Manually send coverage reports to coveralls.
  - ls  coverage/*/lcov.info | cat
  - cat coverage/*/lcov.info | ./node_modules/.bin/coveralls || echo "Coveralls upload failed"
